sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ngITZrf1v0sjyr8KfISZ8gTy+gV0PiCdsU2y7eWM6dn7HcMgxC+1SlTbalqiJKdtQoGgGCMHK3TY0dTEKhw/Ns5xKvOWsP2GPhdzKP6vNOqzK4jVn/34A/CoUHouEtVF1tifkQDaCC5SZ6MdCMdtzlcNA5CZQIpzEELPgc7RrXIxtA9UfdGj+AD4iiJR0C8meWpb5OPFuh3+jJ8mJAlY0mZU/8w7Nd7ZfDEtR3WrwH1qSbJI950uknfmGPz1fX8s7yRmUPagp/G3udVMXlYdL74GUYFacktMIX0HX8nWcCSLQ1qUKSF+GT9/byJpNl9sAyg1Myl5VJGAP1ukNqb8OWKxDOcoog85QQMfklqz+8+Nax+7Yzw1cPPnXcbjIpifK/hAW8HxwiuraN7koTK4J4+lSwEiYiH2BmbnjqS6NtQUnmCmOoWYJP2bRCbqB+jNZ5lFJYjty4+Y1T2Sm1FsU2GQfL3TMlYU3ZeUNMEcJrdcTxlOTaXYMzVtFlXfGH9gUPFgNC7Bbj0B1+ZEHUuSlNMaGsKsy2j+cWnKayb0EBU9Mkqm/Jkd/U+q5t8WlxZWPFpxL4kDdfDZkgOJ4NGu3Fm/SowbTbCvZFjlAhpuU3QjbF8oeJ05Sxs4hQM2iKCpyZauG3GBO3nQLS89x9yATpJNuNEgxYAUErL1eBSbpc4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Where-No-Fear-Was--A-Book-About-Fear_4611
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy